name: Deploy to Heroku

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened,reopened]

env:
  HEROKU_APP_NAME: my-first-test-project

jobs:
  #Push to Heroku
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env vars (development)
        run: |
          echo "IMAGE_NAME=articles-container" >> $GITHUB_ENV
          


      - name: Build image
        run: docker build . -f deploy/Dockerfile -t $IMAGE_NAME 

      - name: Heroku Deploy
        env: 
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku container:login
          docker tag $IMAGE_NAME registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          heroku container:release -a $HEROKU_APP_NAME web